[server]
maxUploadSize = 500 #MB
maxMessageSize = 500 #MB
# enableXsrfProtection = false   # TEMPORARY for debugging
# enableCORS = false             # TEMPORARY for debugging

[theme]
base = "light"                 
